-- Snowflake PROD bootstrap for Python workloads
--
-- Purpose:
-- Create runtime role, warehouse, database, and schema for Python execution.
-- This script is safe to run multiple times.
--
-- Run as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------------
-- 1) Core runtime objects
-- ------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS ROLE_PROD_PYTHON;

CREATE WAREHOUSE IF NOT EXISTS WH_PROD_PYTHON
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ANALYTICS_PROD;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.PYTHON;

-- Used by git integration/bootstrap scripts and repository objects.
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.INTEGRATION;
CREATE SCHEMA IF NOT EXISTS ANALYTICS_PROD.SECURITY;

-- ------------------------------------------------------------------
-- 2) Grants for Python runtime role
-- ------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE WH_PROD_PYTHON TO ROLE ROLE_PROD_PYTHON;
GRANT OPERATE ON WAREHOUSE WH_PROD_PYTHON TO ROLE ROLE_PROD_PYTHON;

GRANT USAGE ON DATABASE ANALYTICS_PROD TO ROLE ROLE_PROD_PYTHON;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.PYTHON TO ROLE ROLE_PROD_PYTHON;
GRANT CREATE PROCEDURE ON SCHEMA ANALYTICS_PROD.PYTHON TO ROLE ROLE_PROD_PYTHON;
GRANT CREATE FUNCTION ON SCHEMA ANALYTICS_PROD.PYTHON TO ROLE ROLE_PROD_PYTHON;
GRANT CREATE TABLE ON SCHEMA ANALYTICS_PROD.PYTHON TO ROLE ROLE_PROD_PYTHON;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.INTEGRATION TO ROLE ROLE_PROD_PYTHON;
GRANT CREATE GIT REPOSITORY ON SCHEMA ANALYTICS_PROD.INTEGRATION TO ROLE ROLE_PROD_PYTHON;

GRANT USAGE ON SCHEMA ANALYTICS_PROD.SECURITY TO ROLE ROLE_PROD_PYTHON;

-- Optional user mapping (replace username):
-- GRANT ROLE ROLE_PROD_PYTHON TO USER <YOUR_SNOWFLAKE_USERNAME>;
