-- Bootstrap current executing user for local Python runs
-- Purpose:
-- - grant ROLE_DEV_PYTHON to CURRENT_USER()
-- - set default role/warehouse/namespace for this user
--
-- Run as SECURITYADMIN (or a role that can GRANT ROLE / ALTER USER).

USE ROLE SECURITYADMIN;

BEGIN
  LET EXECUTING_USER STRING := CURRENT_USER();

  EXECUTE IMMEDIATE
    'GRANT ROLE ROLE_DEV_PYTHON TO USER "' || EXECUTING_USER || '"';

  EXECUTE IMMEDIATE
    'ALTER USER "' || EXECUTING_USER || '" SET DEFAULT_ROLE = ROLE_DEV_PYTHON';

  EXECUTE IMMEDIATE
    'ALTER USER "' || EXECUTING_USER || '" SET DEFAULT_WAREHOUSE = WH_DEV_PYTHON';

  EXECUTE IMMEDIATE
    'ALTER USER "' || EXECUTING_USER || '" SET DEFAULT_NAMESPACE = PLATFORM_DEV.PYTHON';
END;
