-- Snowflake DEV bootstrap for Python workloads
--
-- Purpose:
-- Create runtime role, warehouse, database, and schema for Python execution.
-- This script is safe to run multiple times.
--
-- Run as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;

-- ------------------------------------------------------------------
-- 1) Core runtime objects
-- ------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS ROLE_DEV_PYTHON;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV_PYTHON
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PLATFORM_DEV;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.PYTHON;

-- Used by git integration/bootstrap scripts and repository objects.
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.INTEGRATION;
CREATE SCHEMA IF NOT EXISTS PLATFORM_DEV.SECURITY;

-- ------------------------------------------------------------------
-- 2) Grants for Python runtime role
-- ------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE WH_DEV_PYTHON TO ROLE ROLE_DEV_PYTHON;
GRANT OPERATE ON WAREHOUSE WH_DEV_PYTHON TO ROLE ROLE_DEV_PYTHON;

GRANT USAGE ON DATABASE PLATFORM_DEV TO ROLE ROLE_DEV_PYTHON;

GRANT USAGE ON SCHEMA PLATFORM_DEV.PYTHON TO ROLE ROLE_DEV_PYTHON;
GRANT CREATE PROCEDURE ON SCHEMA PLATFORM_DEV.PYTHON TO ROLE ROLE_DEV_PYTHON;
GRANT CREATE FUNCTION ON SCHEMA PLATFORM_DEV.PYTHON TO ROLE ROLE_DEV_PYTHON;
GRANT CREATE TABLE ON SCHEMA PLATFORM_DEV.PYTHON TO ROLE ROLE_DEV_PYTHON;

GRANT USAGE ON SCHEMA PLATFORM_DEV.INTEGRATION TO ROLE ROLE_DEV_PYTHON;
GRANT CREATE GIT REPOSITORY ON SCHEMA PLATFORM_DEV.INTEGRATION TO ROLE ROLE_DEV_PYTHON;

GRANT USAGE ON SCHEMA PLATFORM_DEV.SECURITY TO ROLE ROLE_DEV_PYTHON;
