-- Bootstrap application secrets for demo Python procedure
--
-- Purpose:
-- - create CLIENT_ID, CLIENT_SECRET, JWT_ASSERTION secrets
-- - grant ROLE_DEV_PYTHON permission to read them
--
-- Run as SECURITYADMIN.

USE ROLE SECURITYADMIN;
USE DATABASE PLATFORM_DEV;
USE SCHEMA SECURITY;

CREATE OR REPLACE SECRET CLIENT_ID
  TYPE = GENERIC_STRING
  SECRET_STRING = '<YOUR_CLIENT_ID>';

CREATE OR REPLACE SECRET CLIENT_SECRET
  TYPE = GENERIC_STRING
  SECRET_STRING = '<YOUR_CLIENT_SECRET>';

CREATE OR REPLACE SECRET JWT_ASSERTION
  TYPE = GENERIC_STRING
  SECRET_STRING = '<YOUR_JWT_ASSERTION>';

GRANT READ ON SECRET CLIENT_ID TO ROLE ROLE_DEV_PYTHON;
GRANT READ ON SECRET CLIENT_SECRET TO ROLE ROLE_DEV_PYTHON;
GRANT READ ON SECRET JWT_ASSERTION TO ROLE ROLE_DEV_PYTHON;
